export const CURRENCY_SYMBOLS: any = {
    AED: 'د.إ',
    AFN: '؋',
    ALL: 'L',
    AMD: '֏',
    ANG: 'ƒ',
    AOA: 'Kz',
    ARS: '$',
    AUD: '$',
    AWG: 'ƒ',
    AZN: '₼',
    BAM: 'KM',
    BBD: '$',
    BDT: '৳',
    BGN: 'лв',
    BHD: '.د.ب',
    BIF: 'FBu',
    BMD: '$',
    BND: '$',
    BOB: '$b',
    BOV: 'BOV',
    BRL: 'R$',
    BSD: '$',
    BTC: '₿',
    BTN: 'Nu.',
    BWP: 'P',
    BYN: 'Br',
    BYR: 'Br',
    BZD: 'BZ$',
    CAD: '$',
    CDF: 'FC',
    CHE: 'CHE',
    CHF: 'CHF',
    CHW: 'CHW',
    CLF: 'CLF',
    CLP: '$',
    CNH: '¥',
    CNY: '¥',
    COP: '$',
    COU: 'COU',
    CRC: '₡',
    CUC: '$',
    CUP: '₱',
    CVE: '$',
    CZK: 'Kč',
    DJF: 'Fdj',
    DKK: 'kr',
    DOP: 'RD$',
    DZD: 'دج',
    EEK: 'kr',
    EGP: '£',
    ERN: 'Nfk',
    ETB: 'Br',
    ETH: 'Ξ',
    EUR: '€',
    FJD: '$',
    FKP: '£',
    GBP: '£',
    GEL: '₾',
    GGP: '£',
    GHC: '₵',
    GHS: 'GH₵',
    GIP: '£',
    GMD: 'D',
    GNF: 'FG',
    GTQ: 'Q',
    GYD: '$',
    HKD: '$',
    HNL: 'L',
    HRK: 'kn',
    HTG: 'G',
    HUF: 'Ft',
    IDR: 'Rp',
    ILS: '₪',
    IMP: '£',
    INR: '₹',
    IQD: 'ع.د',
    IRR: '﷼',
    ISK: 'kr',
    JEP: '£',
    JMD: 'J$',
    JOD: 'JD',
    JPY: '¥',
    KES: 'KSh',
    KGS: 'лв',
    KHR: '៛',
    KMF: 'CF',
    KPW: '₩',
    KRW: '₩',
    KWD: 'KD',
    KYD: '$',
    KZT: '₸',
    LAK: '₭',
    LBP: '£',
    LKR: '₨',
    LRD: '$',
    LSL: 'M',
    LTC: 'Ł',
    LTL: 'Lt',
    LVL: 'Ls',
    LYD: 'LD',
    MAD: 'MAD',
    MDL: 'lei',
    MGA: 'Ar',
    MKD: 'ден',
    MMK: 'K',
    MNT: '₮',
    MOP: 'MOP$',
    MRO: 'UM',
    MRU: 'UM',
    MUR: '₨',
    MVR: 'Rf',
    MWK: 'MK',
    MXN: '$',
    MXV: 'MXV',
    MYR: 'RM',
    MZN: 'MT',
    NAD: '$',
    NGN: '₦',
    NIO: 'C$',
    NOK: 'kr',
    NPR: '₨',
    NZD: '$',
    OMR: '﷼',
    PAB: 'B/.',
    PEN: 'S/.',
    PGK: 'K',
    PHP: '₱',
    PKR: '₨',
    PLN: 'zł',
    PYG: 'Gs',
    QAR: '﷼',
    RMB: '￥',
    RON: 'lei',
    RSD: 'Дин.',
    RUB: '₽',
    RWF: 'R₣',
    SAR: '﷼',
    SBD: '$',
    SCR: '₨',
    SDG: 'ج.س.',
    SEK: 'kr',
    SGD: 'S$',
    SHP: '£',
    SLL: 'Le',
    SOS: 'S',
    SRD: '$',
    SSP: '£',
    STD: 'Db',
    STN: 'Db',
    SVC: '$',
    SYP: '£',
    SZL: 'E',
    THB: '฿',
    TJS: 'SM',
    TMT: 'T',
    TND: 'د.ت',
    TOP: 'T$',
    TRL: '₤',
    TRY: '₺',
    TTD: 'TT$',
    TVD: '$',
    TWD: 'NT$',
    TZS: 'TSh',
    UAH: '₴',
    UGX: 'USh',
    USD: '$',
    UYI: 'UYI',
    UYU: '$U',
    UYW: 'UYW',
    UZS: 'лв',
    VEF: 'Bs',
    VES: 'Bs.S',
    VND: '₫',
    VUV: 'VT',
    WST: 'WS$',
    XAF: 'FCFA',
    XBT: 'Ƀ',
    XCD: '$',
    XOF: 'CFA',
    XPF: '₣',
    XSU: 'Sucre',
    XUA: 'XUA',
    YER: '﷼',
    ZAR: 'R',
    ZMW: 'ZK',
    ZWD: 'Z$',
    ZWL: '$'
}

export const CURRENCY_OPTIONS = Object.keys(CURRENCY_SYMBOLS).map((key) => ({
    value: key,
    label: `${key} - ${CURRENCY_SYMBOLS[key]}`,
}));

export const COUNTRIES: { name: string, currency: string }[] = [
  { "name": "Afghanistan", "currency": "AFN" },
  { "name": "Albania", "currency": "ALL" },
  { "name": "Algeria", "currency": "DZD" },
  { "name": "Andorra", "currency": "EUR" },
  { "name": "Angola", "currency": "AOA" },
  { "name": "Antigua and Barbuda", "currency": "XCD" },
  { "name": "Argentina", "currency": "ARS" },
  { "name": "Armenia", "currency": "AMD" },
  { "name": "Australia", "currency": "AUD" },
  { "name": "Austria", "currency": "EUR" },
  { "name": "Azerbaijan", "currency": "AZN" },
  { "name": "Bahamas", "currency": "BSD" },
  { "name": "Bahrain", "currency": "BHD" },
  { "name": "Bangladesh", "currency": "BDT" },
  { "name": "Barbados", "currency": "BBD" },
  { "name": "Belarus", "currency": "BYN" },
  { "name": "Belgium", "currency": "EUR" },
  { "name": "Belize", "currency": "BZD" },
  { "name": "Benin", "currency": "XOF" },
  { "name": "Bhutan", "currency": "BTN" },
  { "name": "Bolivia", "currency": "BOB" },
  { "name": "Bosnia and Herzegovina", "currency": "BAM" },
  { "name": "Botswana", "currency": "BWP" },
  { "name": "Brazil", "currency": "BRL" },
  { "name": "Brunei", "currency": "BND" },
  { "name": "Bulgaria", "currency": "BGN" },
  { "name": "Burkina Faso", "currency": "XOF" },
  { "name": "Burundi", "currency": "BIF" },
  { "name": "Cambodia", "currency": "KHR" },
  { "name": "Cameroon", "currency": "XAF" },
  { "name": "Canada", "currency": "CAD" },
  { "name": "Cape Verde", "currency": "CVE" },
  { "name": "Central African Republic", "currency": "XAF" },
  { "name": "Chad", "currency": "XAF" },
  { "name": "Chile", "currency": "CLP" },
  { "name": "China", "currency": "CNY" },
  { "name": "Colombia", "currency": "COP" },
  { "name": "Comoros", "currency": "KMF" },
  { "name": "Congo (Brazzaville)", "currency": "XAF" },
  { "name": "Congo (Kinshasa)", "currency": "CDF" },
  { "name": "Costa Rica", "currency": "CRC" },
  { "name": "Croatia", "currency": "EUR" },
  { "name": "Cuba", "currency": "CUP" },
  { "name": "Cyprus", "currency": "EUR" },
  { "name": "Czech Republic", "currency": "CZK" },
  { "name": "Denmark", "currency": "DKK" },
  { "name": "Djibouti", "currency": "DJF" },
  { "name": "Dominica", "currency": "XCD" },
  { "name": "Dominican Republic", "currency": "DOP" },
  { "name": "Ecuador", "currency": "USD" },
  { "name": "Egypt", "currency": "EGP" },
  { "name": "El Salvador", "currency": "USD" },
  { "name": "Equatorial Guinea", "currency": "XAF" },
  { "name": "Eritrea", "currency": "ERN" },
  { "name": "Estonia", "currency": "EUR" },
  { "name": "Eswatini", "currency": "SZL" },
  { "name": "Ethiopia", "currency": "ETB" },
  { "name": "Fiji", "currency": "FJD" },
  { "name": "Finland", "currency": "EUR" },
  { "name": "France", "currency": "EUR" },
  { "name": "Gabon", "currency": "XAF" },
  { "name": "Gambia", "currency": "GMD" },
  { "name": "Georgia", "currency": "GEL" },
  { "name": "Germany", "currency": "EUR" },
  { "name": "Ghana", "currency": "GHS" },
  { "name": "Greece", "currency": "EUR" },
  { "name": "Grenada", "currency": "XCD" },
  { "name": "Guatemala", "currency": "GTQ" },
  { "name": "Guinea", "currency": "GNF" },
  { "name": "Guinea-Bissau", "currency": "XOF" },
  { "name": "Guyana", "currency": "GYD" },
  { "name": "Haiti", "currency": "HTG" },
  { "name": "Honduras", "currency": "HNL" },
  { "name": "Hungary", "currency": "HUF" },
  { "name": "Iceland", "currency": "ISK" },
  { "name": "India", "currency": "INR" },
  { "name": "Indonesia", "currency": "IDR" },
  { "name": "Iran", "currency": "IRR" },
  { "name": "Iraq", "currency": "IQD" },
  { "name": "Ireland", "currency": "EUR" },
  { "name": "Israel", "currency": "ILS" },
  { "name": "Italy", "currency": "EUR" },
  { "name": "Jamaica", "currency": "JMD" },
  { "name": "Japan", "currency": "JPY" },
  { "name": "Jordan", "currency": "JOD" },
  { "name": "Kazakhstan", "currency": "KZT" },
  { "name": "Kenya", "currency": "KES" },
  { "name": "Kiribati", "currency": "AUD" },
  { "name": "Kuwait", "currency": "KWD" },
  { "name": "Kyrgyzstan", "currency": "KGS" },
  { "name": "Laos", "currency": "LAK" },
  { "name": "Latvia", "currency": "EUR" },
  { "name": "Lebanon", "currency": "LBP" },
  { "name": "Lesotho", "currency": "LSL" },
  { "name": "Liberia", "currency": "LRD" },
  { "name": "Libya", "currency": "LYD" },
  { "name": "Liechtenstein", "currency": "CHF" },
  { "name": "Lithuania", "currency": "EUR" },
  { "name": "Luxembourg", "currency": "EUR" },
  { "name": "Madagascar", "currency": "MGA" },
  { "name": "Malawi", "currency": "MWK" },
  { "name": "Malaysia", "currency": "MYR" },
  { "name": "Maldives", "currency": "MVR" },
  { "name": "Mali", "currency": "XOF" },
  { "name": "Malta", "currency": "EUR" },
  { "name": "Mauritania", "currency": "MRU" },
  { "name": "Mauritius", "currency": "MUR" },
  { "name": "Mexico", "currency": "MXN" },
  { "name": "Moldova", "currency": "MDL" },
  { "name": "Monaco", "currency": "EUR" },
  { "name": "Mongolia", "currency": "MNT" },
  { "name": "Montenegro", "currency": "EUR" },
  { "name": "Morocco", "currency": "MAD" },
  { "name": "Mozambique", "currency": "MZN" },
  { "name": "Myanmar", "currency": "MMK" },
  { "name": "Namibia", "currency": "NAD" },
  { "name": "Nauru", "currency": "AUD" },
  { "name": "Nepal", "currency": "NPR" },
  { "name": "Netherlands", "currency": "EUR" },
  { "name": "New Zealand", "currency": "NZD" },
  { "name": "Nicaragua", "currency": "NIO" },
  { "name": "Niger", "currency": "XOF" },
  { "name": "Nigeria", "currency": "NGN" },
  { "name": "North Macedonia", "currency": "MKD" },
  { "name": "Norway", "currency": "NOK" },
  { "name": "Oman", "currency": "OMR" },
  { "name": "Pakistan", "currency": "PKR" },
  { "name": "Palau", "currency": "USD" },
  { "name": "Panama", "currency": "PAB" },
  { "name": "Papua New Guinea", "currency": "PGK" },
  { "name": "Paraguay", "currency": "PYG" },
  { "name": "Peru", "currency": "PEN" },
  { "name": "Philippines", "currency": "PHP" },
  { "name": "Poland", "currency": "PLN" },
  { "name": "Portugal", "currency": "EUR" },
  { "name": "Qatar", "currency": "QAR" },
  { "name": "Romania", "currency": "RON" },
  { "name": "Russia", "currency": "RUB" },
  { "name": "Rwanda", "currency": "RWF" },
  { "name": "Saint Kitts and Nevis", "currency": "XCD" },
  { "name": "Saint Lucia", "currency": "XCD" },
  { "name": "Saint Vincent and the Grenadines", "currency": "XCD" },
  { "name": "Samoa", "currency": "WST" },
  { "name": "San Marino", "currency": "EUR" },
  { "name": "Sao Tome and Principe", "currency": "STN" },
  { "name": "Saudi Arabia", "currency": "SAR" },
  { "name": "Senegal", "currency": "XOF" },
  { "name": "Serbia", "currency": "RSD" },
  { "name": "Seychelles", "currency": "SCR" },
  { "name": "Sierra Leone", "currency": "SLL" },
  { "name": "Singapore", "currency": "SGD" },
  { "name": "Slovakia", "currency": "EUR" },
  { "name": "Slovenia", "currency": "EUR" },
  { "name": "Solomon Islands", "currency": "SBD" },
  { "name": "Somalia", "currency": "SOS" },
  { "name": "South Africa", "currency": "ZAR" },
  { "name": "South Korea", "currency": "KRW" },
  { "name": "South Sudan", "currency": "SSP" },
  { "name": "Spain", "currency": "EUR" },
  { "name": "Sri Lanka", "currency": "LKR" },
  { "name": "Sudan", "currency": "SDG" },
  { "name": "Suriname", "currency": "SRD" },
  { "name": "Sweden", "currency": "SEK" },
  { "name": "Switzerland", "currency": "CHF" },
  { "name": "Syria", "currency": "SYP" },
  { "name": "Taiwan", "currency": "TWD" },
  { "name": "Tajikistan", "currency": "TJS" },
  { "name": "Tanzania", "currency": "TZS" },
  { "name": "Thailand", "currency": "THB" },
  { "name": "Togo", "currency": "XOF" },
  { "name": "Tonga", "currency": "TOP" },
  { "name": "Trinidad and Tobago", "currency": "TTD" },
  { "name": "Tunisia", "currency": "TND" },
  { "name": "Turkey", "currency": "TRY" },
  { "name": "Turkmenistan", "currency": "TMT" },
  { "name": "Tuvalu", "currency": "AUD" },
  { "name": "Uganda", "currency": "UGX" },
  { "name": "Ukraine", "currency": "UAH" },
  { "name": "United Arab Emirates", "currency": "AED" },
  { "name": "United Kingdom", "currency": "GBP" },
  { "name": "United States", "currency": "USD" },
  { "name": "Uruguay", "currency": "UYU" },
  { "name": "Uzbekistan", "currency": "UZS" },
  { "name": "Vanuatu", "currency": "VUV" },
  { "name": "Vatican City", "currency": "EUR" },
  { "name": "Venezuela", "currency": "VES" },
  { "name": "Vietnam", "currency": "VND" },
  { "name": "Yemen", "currency": "YER" },
  { "name": "Zambia", "currency": "ZMW" },
  { "name": "Zimbabwe", "currency": "ZWL" }
]
